// Golden cross-test: the browser core must produce byte-identical names,
// binary IDs, URLs, and word aliases to the Python reference.
// Run: node web/test/golden.mjs   (vectors generated by the Python suite)

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { parse, name } from "../lib/names.js";
import { encode, toUrl, fromUrl, decode } from "../lib/encode.js";
import { alias, fullAlias } from "../lib/words.js";
import { cellSpan } from "../lib/cells.js";
import { phase, children, phaseSubset } from "../lib/core.js";
import { Frac, F } from "../lib/rat.js";

const here = dirname(fileURLToPath(import.meta.url));
const golden = JSON.parse(readFileSync(join(here, "golden.json"), "utf8"));

const hex = (u8) => [...u8].map((b) => b.toString(16).padStart(2, "0")).join("");
let failures = 0;
const check = (label, got, want) => {
  if (JSON.stringify(got) !== JSON.stringify(want)) {
    console.error(`FAIL ${label}\n  got:  ${JSON.stringify(got)}\n  want: ${JSON.stringify(want)}`);
    failures++;
  }
};

for (const [key, g] of Object.entries(golden)) {
  if (key.startsWith("_")) continue;
  const obj = parse(g.name);
  check(`${key} name round-trip`, name(obj), g.name);
  check(`${key} binary`, hex(encode(obj)), g.hex);
  check(`${key} url`, toUrl(obj), g.url);
  check(`${key} url decode`, name(fromUrl(g.url)), g.name);
  check(`${key} binary decode`, name(decode(encode(obj))), g.name);
  check(`${key} full alias`, fullAlias(obj), g.full_alias);
  check(`${key} alias`, alias(obj), g.alias);
}

// UTC cell resolution matches the Python worked examples
check("hour cell span", name(cellSpan(parse("ic1:g:2026-08-01T14"))),
  "ic1:s:1785592837;1785596437");
check("isoweek span", name(cellSpan(parse("ic1:g:2026-W31"))),
  "ic1:s:1785110437;1785715237");
check("leap day duration",
  cellSpan(parse("ic1:g:2016-12-31")).duration.toString(), "86401");
check("leap second cell",
  cellSpan(parse("ic1:g:2016-12-31T23:59:60")).duration.toString(), "1");

// UTC cron occurrences must match Python's civil-lens resolution exactly
// (including the 61-second leap minute).
const { fromCron, cronNextAfter } = await import("../lib/cron.js");
for (const v of golden._cron_next ?? []) {
  const s = fromCron(v.expr);
  let t = Frac.parse(v.from);
  for (const [wantStart, wantEnd] of v.occurrences) {
    const occ = cronNextAfter(s, t);
    check(`cron '${v.expr}' next after ${t}`,
      [occ.start.toString(), occ.end.toString()], [wantStart, wantEnd]);
    t = occ.start;
  }
}

// lattice sanity in JS
const c = phase(Frac.parse("1/3"), 3, { k: 2 });
check("state sugar", c.state, 2);
for (const kid of children(c, 4)) {
  check(`child ⊆ parent (${name(kid)})`, phaseSubset(kid, c), true);
}
check("non-subset", phaseSubset(c, children(c, 4)[0]), false);

if (failures) {
  console.error(`\n${failures} failure(s)`);
  process.exit(1);
}
console.log(`ALL GOLDEN CROSS-TESTS PASSED (${Object.keys(golden).length} vectors, TS↔Python byte-identical)`);
